config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :features

  resources :dealerships do
    resources :cars do
      member do
        post :create_comment
        delete :delete_comment
        put :sell_car
        put :reserve
        put :reneg        
      end
    end

    member do
      post :create_comment
      delete :delete_comment
    end
  end

  root 'welcome#index'

  get '/cars' => 'cars#search_cars'

end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
  has_many :cars#, dependent: :destroy
  has_many :comments, as: :commentable

  validates :name, presence: true, if: Proc.new { |dealership| hey_manny?; dealership.name.include?("Belinda") }

  def hey_manny?
    p self
  end

  geocoded_by :address
  after_validation :geocode
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :authenticate_user!
  respond_to :json, :html
  def index
    @dealerships = Dealership.all
  end

  def show
    @dealership = Dealership.find params[:id]
    @cars = @dealership.cars.includes(:features)
    @comment = @dealership.comments.new
    respond_to do |format|
      format.js
    end
  end

  def new
    @dealership = Dealership.new
  end

  def create
    @dealership = Dealership.new dealership_params
    if @dealership.save
      redirect_to dealerships_path
    else
      render :new
    end
  end

  def edit
    @dealership = Dealership.find params[:id]
  end

  def update
    @dealership = Dealership.find params[:id]
    @dealership.update_attributes dealership_params
    redirect_to dealerships_path
  end

  def destroy
    @dealership = Dealership.find params[:id]
    @dealership.delete
    redirect_to dealerships_path
  end

  def create_comment
    @dealership = Dealership.find params[:id]
    @dealership.comments.create comment_params
    # dealership_path(@dealership)
    redirect_to @dealership
  end

  def delete_comment
    @dealership = Dealership.find params[:id]
    @comment = Comment.find params[:comment_id]
    @comment.delete
    redirect_to @dealership
  end
private
  def dealership_params
    params.require(:dealership).permit(:name, :description, :address)
  end

  # Whitelisting parameters
  # Strong params - In rails
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/dealerships/_form.html.haml
= form_for @dealership do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :description
  = f.text_field :description
  %br
  = f.label :address
  = f.text_area :address
  %br
  = f.submit "Submit", class: "dealership_submit"

%br
= text_field_tag '', '', class: "bro_name"
= link_to "Add Bro", 'javascript:void(0);', class: "add_bro"
.bros
  %h1.bro Toby

app/views/dealerships/_some_show.html.haml
%h1 Show Dealership
%strong
  Name:
= @dealership.name
%br
%strong
  Description
= @dealership.description
%br
= link_to "Create Car", 'javascript:void(0);', class: "create_car", new_car_path: new_dealership_car_path(@dealership)
%ul
  /= @dealership.cars.inspect
  - @cars.each do |car|
    %li
      = link_to "#{car.full_name} - #{to_money(car.total_cost)}", dealership_car_path(@dealership, car)
      |
      = link_to "Edit", edit_dealership_car_path(@dealership, car)
      |
      = link_to "Delete", dealership_car_path(@dealership, car), method: :delete

%br
= link_to "Back", dealerships_path
%br
Comments
%br
%ul
  - @dealership.comments.each do |comment|
    - if comment.content
      %li
        = comment.content
        = link_to "[Delete]", delete_comment_dealership_path(@dealership, comment_id: comment.id), method: :delete

= form_for @comment, url: create_comment_dealership_path(@dealership) do |f|
  = f.label :content
  = f.text_area :content
  %br
  = f.submit

app/views/dealerships/edit.html.haml
%h1 Edit Dealership

= render 'form'

app/views/dealerships/index.html.haml
.container
  .row
    .col-xs-6
      %h1 Dealerships

      = link_to "Create Dealership", new_dealership_path
      - markers = ''
      %ul
        - @dealerships.each do |dealership|
          %li
            %strong
              = link_to dealership.name, 'javascript:void(0);', class: 'dealership_index_links', dealership_path: dealership_path(dealership)
              / dealership_path(dealership)
            = dealership.description
            |
            = link_to "Edit", edit_dealership_path(dealership)
            |
            = link_to "Delete", dealership_path(dealership), method: :delete
            - markers << "#{dealership.latitude}%2C#{dealership.longitude}&"
      = link_to "Back", root_path

      / = image_tag "http://maps.google.com/maps/api/staticmap?size=1000x1000&sensor=false&markers=#{markers}"
      %ul
        - ['nbucciarelli', 'reynoldsball', 'slwaller', 'lanceorechovesky', 'jvh1979theironyard', 'jgkingston', 'jimrambow', 'belindahare', 'gtlaserbeast'].each do |avatar|
          %li= link_to avatar, 'javascript:void(0);', class: 'avatar_links', avatar_string: avatar
    .col-xs-6.dealership_show_frame
      WE are going to render some dealership show pages

app/views/dealerships/new.html.haml
%h1 New Dealership

= render 'form'

app/views/dealerships/show.html.haml
= render 'some_show'

app/views/dealerships/show.js.erb
$('.dealership_show_frame').html("<%= escape_javascript( render( 'dealerships/some_show' )) %> ");