config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :features

  resources :dealerships do
    resources :cars do
      member do
        post :create_comment
        delete :delete_comment
        put :sell_car
        put :reserve
        put :reneg        
      end
    end

    member do
      post :create_comment
      delete :delete_comment
    end
  end

  root 'welcome#index'

  get '/cars' => 'cars#search_cars'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :dealership
  has_many :comments, as: :commentable

  has_many :car_features
  has_many :features, through: :car_features

  include Workflow
  workflow do
    state :for_sale do
      event :reserve, transitions_to: :reserved
      event :sell, transitions_to: :sold
    end
    state :reserved do
      event :reneg, transitions_to: :for_sale
      event :sell, transitions_to: :sold
    end
    state :sold
  end

  def full_name
    "#{make} - #{model} - #{year}"
  end

  def total_cost
    self.base_cost + self.total_feature_cost
  end

  def total_feature_cost
    current_total = 0.0
    self.features.each do |feature|
      current_total += feature.cost
    end
    current_total.round(2)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy, :sell_car, :reserve, :reneg]

  # before_action :set_dealership

  def search_cars
    @cars = Car.where("make LIKE ?", "%#{params[:q]}%")
    respond_to do |format|
      format.js
    end
  end

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @dealership = Dealership.find params[:dealership_id] if params[:dealership_id] != 'ajax'
    respond_to do |format|
      format.js
      format.html
    end

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    p '*'*100
    p params
    @dealership = Dealership.find params[:dealership_id]
    @comment = @car.comments.new
  end

  # GET /cars/new
  def new
    @car = Car.new
    @dealership = Dealership.find params[:dealership_id]
    @features = Feature.all
    respond_to do |format|
      format.js
    end    
  end

  # GET /cars/1/edit
  def edit
    @dealership = Dealership.find params[:dealership_id]
    @features = Feature.all
  end

  # POST /cars
  # POST /cars.json
  def create
    
    @dealership = Dealership.find params[:dealership_id]
    # This will create a new car object OFF OF THE DEALERSHIP. So it will create the relationship between the two.
    # Car.new({make: "Honda", dealership_id: @dealership.id})
    @car = @dealership.cars.new(car_params)
    # p @dealership.cars
    respond_to do |format|
      if @car.save
        flash[:notice] = "Car was successfully created"
        format.html { redirect_to dealership_path(@dealership) }
      else
        flash[:error] = "Car was not successfully created"
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @dealership = Dealership.find params[:dealership_id]
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to dealership_path(@dealership), notice: 'Car was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @dealership = Dealership.find params[:dealership_id]
    @car.destroy
    respond_to do |format|
      format.html { redirect_to dealership_path(@dealership), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sell_car
    @dealership = Dealership.find params[:dealership_id]
    # @car = Car.find params[:id]
    @car.sell!
    # redirect_to dealership_car_path(@dealership, @car)
    respond_to do |format|
      format.js
    end
  end

  def reserve
    @dealership = Dealership.find params[:dealership_id]
    @car.reserve!
    respond_to do |format|
      format.js
    end
  end

  def reneg
    @dealership = Dealership.find params[:dealership_id]
    @car.reneg!
    respond_to do |format|
      format.js
    end
  end

  def create_comment
    @dealership = Dealership.find params[:dealership_id]
    @car = @dealership.cars.find params[:id]
    @comment = @car.comments.create comment_params
    redirect_to dealership_car_path(@dealership, @car)
  end

  def delete_comment
    p params
    @dealership = Dealership.find params[:dealership_id]
    @car = @dealership.cars.find params[:id]
    @comment = @car.comments.find params[:comment_id]
    @comment.delete
    redirect_to dealership_car_path(@dealership, @car)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # def set_dealership
    #   @dealership = Dealership.find params[:dealership_id]
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(
        :make,
        :model,
        :year,
        :base_cost,
        feature_ids: []
      )
    end
  
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car_partial.html.haml
%li
  = bens_car.make
  |
  = bens_car.model
  |
  / = bens_car.dealership
  = link_to 'Click here', dealership_car_path(bens_car.dealership, bens_car)

app/views/cars/_form.html.haml
New car for 
= @dealership.name
= form_for [@dealership, @car], remote: true do |f|
  - if @car.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :make
    = f.text_field :make
  .field
    = f.label :model
    = f.text_field :model
  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :base_cost
    = f.number_field :base_cost, :step => 0.01
  .field
    %ul
      - @features.each do |feature|
        %li
          / = f.check_box 'car[feature_ids][]'
          = check_box_tag 'car[feature_ids][]', feature.id, @car.features.include?(feature) 
          = feature.name
          |
          = feature.cost
          |
          = feature.description
  .actions
    = f.submit 'Save'

app/views/cars/_workflow_states.html.haml
%strong
  Current State
= @car.workflow_state
%br
- if @car.workflow_state != "sold"
  = link_to "Sell!", 'javascript:void(0);', class: 'sell_car', state_path: sell_car_dealership_car_path(@dealership, @car)
- if !['reserved', 'sold'].include?(@car.workflow_state)
  = link_to "Reserve!", 'javascript:void(0);', class: 'reserve_car', state_path: reserve_dealership_car_path(@dealership, @car)
- if !['for_sale', 'sold'].include?(@car.workflow_state)
  = link_to "Reneg!", 'javascript:void(0);', class: 'reneg_car', state_path: reneg_dealership_car_path(@dealership, @car)

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to 'Back', dealership_path(@dealership)

app/views/cars/index.html.haml
%h1 Listing cars

%table
  %tr
    %th Make
    %th Model
    %th Year
    %th Workflow State
    %th
    %th
    %th
    %th Change State

  - @cars.each do |car|
    %tr
      %td= car.make
      %td= car.model
      %td= car.year
      %td= car.workflow_state
      %td= link_to 'Show', car
      %td= link_to 'Edit', edit_car_path(car)
      %td
        = link_to 'Destroy', car, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td.workflow_state
        - if car.workflow_state != "sold"
          = link_to "Sell!", sell_car_car_path(car), method: :put
        - if !['reserved', 'sold'].include?(car.workflow_state)
          = link_to "Reserve!", reserve_car_path(car), method: :put
        - if !['for_sale', 'sold'].include?(car.workflow_state)
          = link_to "Reneg!", reneg_car_path(car), method: :put

%br

= link_to 'New Car', new_car_path

app/views/cars/index.js.erb
<% @cars.each do |car| %>
  $("ul.cars").append("<%= escape_javascript(render('cars/car_partial', bens_car: car )) %>")
<% end %>

app/views/cars/new.html.haml
%h1 New car

= render 'form'

= link_to 'Back', dealerships_path(@dealership)

app/views/cars/new.js.erb
$('.dealership_show_frame').html("<%= escape_javascript( render( 'cars/form' )) %> ");

app/views/cars/reneg.js.erb
console.log("reneg")
console.log($(".workflow_state"))
$('.workflow_state').html("<%= escape_javascript(render('cars/workflow_states' )) %>")

app/views/cars/reserve.js.erb
console.log("resrve")
console.log($(".workflow_state"))
$('.workflow_state').html("<%= escape_javascript(render('cars/workflow_states' )) %>")

app/views/cars/search_cars.js.erb
$("ul.search_list").html("")
<% @cars.each do |car| %>
  $("ul.search_list").append("<%= escape_javascript(render('cars/car_partial', bens_car: car )) %>")
<% end %>

app/views/cars/sell_car.js.erb
console.log("sell car")
$('.workflow_state').html("<%= escape_javascript(render('cars/workflow_states' )) %>")

app/views/cars/show.html.haml
%p
  %strong Make:
  = @car.make
%p
  %strong Model:
  = @car.model
%p
  %strong Year:
  = @car.year
%p
  %strong Dealership
  / = @car.dealership_id
  - if @car.dealership
    / @car.dealership
    = link_to @dealership.try(:name), dealership_path(@dealership)
%p
  %strong Features
  %ul
    - @car.features.each do |feature|
      %li
        = feature.name
        |
        = to_money(feature.cost)
%p
  %strong Total Feature Cost
  = to_money(@car.total_feature_cost)
/ @car.dealership
= link_to 'Back', dealership_path(@dealership)
%br
%ul
  - @car.comments.each do |comment|
    - if comment.content
      %li
        = comment.content
        = link_to "[Delete]", delete_comment_dealership_car_path(@dealership, @car, comment_id: comment.id, john_hammond: "not from jurrasic park"), method: :delete


.workflow_state
  = render 'workflow_states' 
= form_for @comment, url: create_comment_dealership_car_path(@dealership, @car) do |f|
  = f.label :content
  = f.text_area :content
  %br
  = f.submit