config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :features

  resources :dealerships do
    resources :cars do
      member do
        post :create_comment
        delete :delete_comment
        put :sell_car
        put :reserve
        put :reneg        
      end
    end

    member do
      post :create_comment
      delete :delete_comment
    end
  end

  root 'welcome#index'

  get '/cars' => 'cars#search_cars'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :car_features
  has_many :cars, through: :car_features
  # has_and_belongs_to_many
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name, :cost, :description)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.haml
= form_for @feature do |f|
  - if @feature.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feature.errors.count, "error")} prohibited this feature from being saved:"
      %ul
        - @feature.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control", placeholder: "PLease fill out your name"
  .form-group
    = f.label :cost
    = f.text_field :cost, class: "form-control"
  .form-group    
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group    
    = f.submit 'Save'

app/views/features/edit.html.haml
%h1 Editing feature

= render 'form'

= link_to 'Show', @feature
\|
= link_to 'Back', features_path

app/views/features/index.html.haml
%h1 Listing features

%table
  %tr
    %th Name
    %th Cost
    %th Description
    %th
    %th
    %th

  - @features.each do |feature|
    %tr
      %td= feature.name
      %td= feature.cost
      %td= feature.description
      %td= link_to 'Show', feature
      %td= link_to 'Edit', edit_feature_path(feature)
      %td= link_to 'Destroy', feature, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feature', new_feature_path
= link_to 'Back', root_path

app/views/features/new.html.haml
%h1 New feature

= render 'form'

= link_to 'Back', features_path

app/views/features/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @feature.name
%p
  %b Cost:
  = @feature.cost
%p
  %b Description:
  = @feature.description
%p
  %strong Cars
  %ul
    - @feature.cars.each do |car|
      %li
        = car.make
        |
        = car.model


= link_to 'Edit', edit_feature_path(@feature)
\|
= link_to 'Back', features_path